name: Build macOS PKG

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build macOS PKG
      run: |
        make pkg

    - name: Upload PKG as GitHub Artifact (Internal)
      uses: actions/upload-artifact@v4
      with:
        name: BingWallpaper-macOS.pkg
        path: BingWallpaper-macOS.pkg
        
    - name: Publish Public GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: BingWallpaper-macOS.pkg
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
